if(DEFINED mcuboot_TARGET_DTC_OVERLAY_FILE)
  list(APPEND mcuboot_DTC_OVERLAY_FILE
       "${CMAKE_CURRENT_LIST_DIR}/sysbuild/mcuboot/${mcuboot_TARGET_DTC_OVERLAY_FILE}")
  list(REMOVE_DUPLICATES mcuboot_DTC_OVERLAY_FILE)
  set(mcuboot_DTC_OVERLAY_FILE "${mcuboot_DTC_OVERLAY_FILE}" CACHE INTERNAL "")
endif()
